### ISSUE TITLE
EMU-2 with single USB for power does not appear as a serial device 

### ISSUE THREAD

**Issue by ckrintz** [rainforestautomation/Emu-Serial-API#2]
Hi
I purchased an EMU-2 from Amazon at the link specified in the readme.  It came with a single microUSB (vs the original dual setup).  It connects/reports my power data correctly but there is no USB serial device in /dev (I typically see a ttyUSB0 or some such).  I tried the ones that are there /dev/ttyATA0 and /dev/ttyS0 but the utility reports "having trouble connecting to serial....1" then throws an exception and hangs.  Does this tool work on the updated EMU-2's?  

>>> from emu import *
>>> instance = emu('/dev/ttyS0')
>>> instance.start_serial()
Starting serial process for EMU on /dev/ttyS0

>>> having trouble connecting to serial....1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "emu.py", line 448, in serial_thread
    text =self.ser.readlines()
AttributeError: emu instance has no attribute 'ser'

**Comment by ckrintz** [comment]
I found the problem: my disk (part of it) somehow got corrupted.  After a reinstall it all worked.  thanks!
